# sample file

# global options
@verbose = true
@default = "hello"

# entries
[chcd]
cwd = "tmp"
command = ["pwd"]

[rmdir]
depends = ["chcd"]
command = ["rmdir", "tmp"]

[duck]
command = ["echo", "ğŸ£ğŸ£ğŸ£"]

[hello]
depends = ["duck", "rmdir"]
command = ["echo", "hello ğŸ¦†"]

