# sample file

# entries
[chcd]
cwd = "tmp"
command.linux = ["pwd"]
command.windows = ["cmd", "/c", "cd"]

[rmdir]
depends = ["chcd"]
command.linux = ["rmdir", "tmp"]
command.windows = ["cmd", "/c", "rmdir", "tmp"]

[duck]
command.linux = ["echo", "ğŸ£ğŸ£ğŸ£"]
command.windows = ["cmd", "/c", "echo", "ooo"]

[run]
depends = ["duck", "rmdir"]
command.linux = ["echo", "hello ğŸ¦†"]
command.windows = ["cmd", "/c", "echo", "hello hello"]

